
package com.codelious.clientejaxb.generados;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "saludarService", targetNamespace = "http://localhost:18080/com/codelious/miws/saludar-service", wsdlLocation = "http://localhost:18080/MiWS/services/saludar.wsdl")
public class SaludarService
    extends Service
{

    private final static URL SALUDARSERVICE_WSDL_LOCATION;
    private final static WebServiceException SALUDARSERVICE_EXCEPTION;
    private final static QName SALUDARSERVICE_QNAME = new QName("http://localhost:18080/com/codelious/miws/saludar-service", "saludarService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:18080/MiWS/services/saludar.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SALUDARSERVICE_WSDL_LOCATION = url;
        SALUDARSERVICE_EXCEPTION = e;
    }

    public SaludarService() {
        super(__getWsdlLocation(), SALUDARSERVICE_QNAME);
    }

    public SaludarService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SALUDARSERVICE_QNAME, features);
    }

    public SaludarService(URL wsdlLocation) {
        super(wsdlLocation, SALUDARSERVICE_QNAME);
    }

    public SaludarService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SALUDARSERVICE_QNAME, features);
    }

    public SaludarService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SaludarService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Saludar
     */
    @WebEndpoint(name = "saludarSoap11")
    public Saludar getSaludarSoap11() {
        return super.getPort(new QName("http://localhost:18080/com/codelious/miws/saludar-service", "saludarSoap11"), Saludar.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Saludar
     */
    @WebEndpoint(name = "saludarSoap11")
    public Saludar getSaludarSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://localhost:18080/com/codelious/miws/saludar-service", "saludarSoap11"), Saludar.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SALUDARSERVICE_EXCEPTION!= null) {
            throw SALUDARSERVICE_EXCEPTION;
        }
        return SALUDARSERVICE_WSDL_LOCATION;
    }

}
