
package com.codelious.clientejaxb.generados;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "saludar", targetNamespace = "http://localhost:18080/com/codelious/miws/saludar-service")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Saludar {


    /**
     * 
     * @param saludoRequest
     * @return
     *     returns localhost._18080.com.codelious.miws.saludar_service.SaludoResponse
     */
    @WebMethod(operationName = "Saludo")
    @WebResult(name = "SaludoResponse", targetNamespace = "http://localhost:18080/com/codelious/miws/saludar-service", partName = "SaludoResponse")
    public SaludoResponse saludo(
        @WebParam(name = "SaludoRequest", targetNamespace = "http://localhost:18080/com/codelious/miws/saludar-service", partName = "SaludoRequest")
        SaludoRequest saludoRequest);

}
